disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "dopeamine.tech"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
#logo = "img/ninjaostrichshippuden.png"
description = "My awesome website"
copyright = "© 2026 dopeamine.tech"

[params.author]
name = "Amine Sabil"
#email = "youremail@example.com"
image = "img/PersonalFace.jpg"
imageQuality = 96
headline = "I'm only human"
bio = "A little bit about you how does it go here right?"
links = [
  { email = "mailto:hello@your_domain.com" },
  { link = "https://link-to-some-website.com/" },
  { github = "https://github.com/fizlewit" },
  { linkedin = "https://www.linkedin.com/in/aminesabil/" },
  { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  { steam = "https://steamcommunity.com/profiles/userid" },
  { telegram = "https://t.me/username" },
]
